<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>Ally Http Engine</AssemblyTitle>
    <Description>Ally Http Engine is a Http processor developed by Elnior Loreh</Description>
    <Company>Codevelp Club</Company>
    <Copyright>(C) Codevelp Club 2026</Copyright>
    <Authors>Codevelp Club | Oxoh Engineering | AHE, Anully on .Netstandard2.0</Authors>
    <Product>AHE</Product>
    <Version>2.0.0.0</Version>
    <FileVersion>3.0.0.0</FileVersion>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>